# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  test:
    docker:
      - image: cimg/clojure:1.10
        auth:
          username: $DOCKERHUB_USERNAME # can specify string literal values
          password: $DOCKERHUB_PASSWORD # or project environment variable reference
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: Test
          command: "clojure -T:build test"
      - store_test_results:
          path: test-results

  deploy-jar:
    docker:
      - image: cimg/clojure:1.10
        auth:
          username: $DOCKERHUB_USERNAME # can specify string literal values
          password: $DOCKERHUB_PASSWORD # or project environment variable reference
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: Build
          command: clojure -T:build build-lib
      - run:
          name: Deploy
          command: |
            if [ -n "${CIRCLE_TAG}" ]; then
               clojure -T:build deploy
            else
               /bin/echo "Not deploying, not a tagged commit"
            fi

  deploy-linux-binary:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
      - checkout
      - run:
          name: Install clojure
          command: |
            wget https://download.clojure.org/install/linux-install-1.11.1.1224.sh
            chmod +x linux-install-1.11.1.1224.sh
            sudo ./linux-install-1.11.1.1224.sh
      - run:
          name: Install graalvm
          command: |
            wget https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.1/graalvm-ce-java17-linux-amd64-22.3.1.tar.gz
            tar -xzf graalvm-ce-java17-linux-amd64-22.3.1.tar.gz
            graalvm-ce-java17-22.3.1/bin/gu install native-image
      - run:
          name: Install ghr
          command: |
            wget https://github.com/tcnksm/ghr/releases/download/v0.16.0/ghr_v0.16.0_linux_amd64.tar.gz
            tar -xzf ghr_v0.16.0_linux_amd64.tar.gz
      - run:
          name: Build
          command: |
            bin/compile
            tar -czpf csv2rdf-linux.tar.gz csv2rdf
          environment:
            GRAALVM_HOME: graalvm-ce-java17-22.3.1
      # Based on https://circleci.com/blog/publishing-to-github-releases-via-circleci/
      - run:
          name: Publish
          command: |
            ghr_v0.16.0_linux_amd64/ghr \
              -u "${CIRCLE_PROJECT_USERNAME}" \
              -r "${CIRCLE_PROJECT_REPONAME}" \
              -c "${CIRCLE_SHA1}" \
              -generatenotes \
              "${CIRCLE_TAG}" \
              csv2rdf-linux

  deploy-darwin-binary:
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - run:
          name: Install clojure
          command: brew install clojure
          environment:
            HOMEBREW_NO_AUTO_UPDATE: 1
      - run:
          name: Install graalvm
          command: |
            wget https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.1/graalvm-ce-java17-darwin-amd64-22.3.1.tar.gz
            tar -xzf graalvm-ce-java17-darwin-amd64-22.3.1.tar.gz
            graalvm-ce-java17-22.3.1/Contents/Home/bin/gu install native-image
      - run:
          name: Install ghr
          command: |
            wget https://github.com/tcnksm/ghr/releases/download/v0.16.0/ghr_v0.16.0_darwin_amd64.zip
            unzip ghr_v0.16.0_darwin_amd64.zip
      - run:
          name: Build
          command: |
            bin/compile
            tar -czpf csv2rdf-darwin.tar.gz csv2rdf
          environment:
            GRAALVM_HOME: graalvm-ce-java17-22.3.1/Contents/Home/
      # Based on https://circleci.com/blog/publishing-to-github-releases-via-circleci/
      - run:
          name: Publish
          command: |
            ghr_v0.16.0_darwin_amd64/ghr \
              -u "${CIRCLE_PROJECT_USERNAME}" \
              -r "${CIRCLE_PROJECT_REPONAME}" \
              -c "${CIRCLE_SHA1}" \
              -generatenotes \
              "${CIRCLE_TAG}" \
              csv2rdf-darwin

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-workflow:
    jobs:
      - test:
          context:
            - swirrl-dockerhub-consumer
          filters:
            tags:
              only: /.*/
      - deploy-jar:
          context:
            - swirrl-dockerhub-consumer
            - swirrl-clojars-publisher
          requires:
            - test
          filters:
            tags:
              only: /.*/
      - deploy-linux-binary:
          context:
            - github-publish-releases
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - deploy-darwin-binary:
          context:
            - github-publish-releases
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
